# -*- coding: utf-8 -*-
"""Inheritance assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oqZgY0bRorE2WIS7Ie8fpemOvPOOr0LF
"""

# ============================================================
#         OOP ASSIGNMENT – Complete Solution (Simple & Easy)
# ============================================================

# ============================================================
# PART A – INHERITANCE
# ============================================================

# 1️⃣ Single Inheritance
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def display(self):
        print(f"Name: {self.name}, Age: {self.age}")

class Student(Person):
    def __init__(self, name, age, grade):
        super().__init__(name, age)
        self.grade = grade

    def display_student(self):
        print(f"Name: {self.name}, Age: {self.age}, Grade: {self.grade}")

print("--- Single Inheritance ---")
s = Student("Ali", 20, "A")
s.display()
s.display_student()


# 2️⃣ Multilevel Inheritance
class Animal:
    def eat(self):
        print("Animal is eating")

class Dog(Animal):
    def bark(self):
        print("Dog is barking")

class BabyDog(Dog):
    def weep(self):
        print("BabyDog is weeping")

print("\n--- Multilevel Inheritance ---")
bd = BabyDog()
bd.eat()
bd.bark()
bd.weep()


# 3️⃣ Hierarchical Inheritance
class Vehicle:
    def info(self):
        print("This is a vehicle")

class Car(Vehicle):
    def car_type(self):
        print("This is a Car")

class Bike(Vehicle):
    def bike_type(self):
        print("This is a Bike")

print("\n--- Hierarchical Inheritance ---")
c = Car()
c.info()
c.car_type()

b = Bike()
b.info()
b.bike_type()


# ============================================================
# PART B – POLYMORPHISM
# ============================================================

# 4️⃣ Method Overriding
class Shape:
    def area(self):
        print("Area of shape")

class Rectangle(Shape):
    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        print(f"Rectangle Area: {self.length * self.width}")

class Circle(Shape):
    def __init__(self, radius):
        self.radius = radius

    def area(self):
        print(f"Circle Area: {3.14 * self.radius * self.radius:.2f}")

print("\n--- Method Overriding ---")
r = Rectangle(5, 3)
r.area()

ci = Circle(7)
ci.area()


# 5️⃣ Operator Overloading
class Number:
    def __init__(self, value):
        self.value = value

    def __add__(self, other):
        # self  = LHS object (n1)
        # other = RHS object (n2)
        return Number(self.value + other.value)

    def display(self):
        print(f"Value: {self.value}")

print("\n--- Operator Overloading ---")
n1 = Number(10)
n2 = Number(20)
n3 = n1 + n2   # calls n1.__add__(n2)
n3.display()

# Explanation:
# self  → refers to the LEFT side object  (n1)
# other → refers to the RIGHT side object (n2) — also called RHS object


# 6️⃣ Polymorphism Using Loop
class Dog2:
    def sound(self):
        print("Dog says: Woof")

class Cat:
    def sound(self):
        print("Cat says: Meow")

class Cow:
    def sound(self):
        print("Cow says: Moo")

print("\n--- Polymorphism Using Loop ---")
animals = [Dog2(), Cat(), Cow()]
for animal in animals:
    animal.sound()


# ============================================================
# PART C – INSTANCE, CLASS & STATIC METHODS
# ============================================================

# 7️⃣ Instance Method
class Employee:
    def __init__(self, name, salary):
        self.name = name
        self.salary = salary

    def display(self):
        print(f"Employee: {self.name}, Salary: {self.salary}")

print("\n--- Instance Method ---")
e = Employee("Ahmed", 50000)
e.display()


# 8️⃣ Class Method
class Company:
    company_name = "TechCorp"

    @classmethod
    def change_company_name(cls, new_name):
        cls.company_name = new_name
        print(f"Company name changed to: {cls.company_name}")

print("\n--- Class Method ---")
Company.change_company_name("NextGen Solutions")


# 9️⃣ Static Method
class MathUtils:
    @staticmethod
    def add(a, b):
        return a + b

    @staticmethod
    def multiply(a, b):
        return a * b

print("\n--- Static Method ---")
print("Add:", MathUtils.add(4, 5))
print("Multiply:", MathUtils.multiply(4, 5))


# ============================================================
# PART D – MAGIC METHODS
# ============================================================

# 🔟 __str__
class Book:
    def __init__(self, title, price):
        self.title = title
        self.price = price

    def __str__(self):
        return f"Book: {self.title}, Price: {self.price}"

print("\n--- Magic Method __str__ ---")
bk = Book("Python Basics", 500)
print(bk)


# 1️⃣1️⃣ __len__
class Playlist:
    def __init__(self, songs):
        self.songs = songs

    def __len__(self):
        return len(self.songs)

print("\n--- Magic Method __len__ ---")
pl = Playlist(["Song A", "Song B", "Song C"])
print("Total songs:", len(pl))


# 1️⃣2️⃣ __repr__
class Product:
    def __init__(self, name, price):
        self.name = name
        self.price = price

    def __repr__(self):
        return f"Product(name={self.name}, price={self.price})"

print("\n--- Magic Method __repr__ ---")
p = Product("Laptop", 75000)
print(repr(p))


# ============================================================
# PART E – MIXED ADVANCED TASK
# ============================================================

# 1️⃣3️⃣ BankAccount System
class BankAccount:
    bank_name = "AlFalah Bank"

    def __init__(self, owner, balance):
        self.owner = owner
        self.__balance = balance   # private attribute (encapsulation)

    def get_balance(self):
        return self.__balance

    def __str__(self):
        return f"Account Owner: {self.owner}, Balance: {self.__balance}"

    def __add__(self, other):
        total = self.__balance + other.__balance
        return BankAccount("Combined", total)

    @classmethod
    def set_bank_name(cls, name):
        cls.bank_name = name
        print(f"Bank name set to: {cls.bank_name}")

    @staticmethod
    def validate_ifsc(ifsc):
        # Simple rule: 11 characters, starts with 4 letters
        if len(ifsc) == 11 and ifsc[:4].isalpha():
            print(f"IFSC {ifsc} is Valid")
        else:
            print(f"IFSC {ifsc} is Invalid")


class SavingsAccount(BankAccount):
    def __init__(self, owner, balance, interest_rate):
        super().__init__(owner, balance)
        self.interest_rate = interest_rate

    def __str__(self):
        return f"[Savings] {super().__str__()}, Interest Rate: {self.interest_rate}%"


class CurrentAccount(BankAccount):
    def __init__(self, owner, balance, overdraft_limit):
        super().__init__(owner, balance)
        self.overdraft_limit = overdraft_limit

    def __str__(self):
        return f"[Current] {super().__str__()}, Overdraft Limit: {self.overdraft_limit}"


print("\n--- BankAccount System ---")
sa = SavingsAccount("Ali", 10000, 5)
ca = CurrentAccount("Sara", 20000, 5000)

print(sa)
print(ca)

combined = sa + ca
print("Combined Account Balance:", combined.get_balance())

BankAccount.set_bank_name("HBL Pakistan")

BankAccount.validate_ifsc("HDFC0001234")
BankAccount.validate_ifsc("123")


# ============================================================
# THEORY / INTERVIEW ANSWERS
# ============================================================
"""
1. Method Overriding vs Method Overloading:
   - Overriding  → Child class redefines parent's method (same name, same params).
   - Overloading → Same method name, different parameters. Python does NOT support
                   traditional overloading; we use default args or *args instead.

2. MRO (Method Resolution Order):
   - The order Python follows to look up methods in inheritance.
   - Python uses C3 Linearization algorithm.
   - Check using: ClassName.__mro__ or help(ClassName)
   - Example: BabyDog → Dog → Animal → object

3. Instance vs Class vs Static Method:
   - Instance Method : works on object data, takes 'self' as first param.
   - Class Method    : works on class data, takes 'cls', uses @classmethod.
   - Static Method   : no access to class or object, uses @staticmethod.

4. If child does NOT override parent method:
   - Python automatically uses the parent class method (inherited as-is).

5. RHS Object in Operator Overloading:
   - In n1 + n2, n1 is LHS (self) and n2 is RHS (other).
   - 'other' represents the object on the RIGHT side of the operator.
"""